name: rehan_rose
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.1.2
  firebase_analytics: ^12.1.1
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  firebase_storage: ^13.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.2.0
  go_router: ^17.0.1
  google_fonts: ^8.0.0
  image_picker: ^1.2.1
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.7.0
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/main_page_01.mp4
