name: rehan_rose
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cloud_firestore: ^6.1.2
  firebase_analytics: ^12.1.1
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  google_sign_in: ^6.2.2
  firebase_storage: ^13.0.6
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.2.0
  go_router: ^17.0.1
  google_fonts: ^8.0.0
  flutter_image_compress: ^2.4.0
  image: ^4.7.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.7.0
  video_player: ^2.9.2
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.1
  flutter_cache_manager: ^3.4.0
  shimmer: ^3.0.0
  seo: ^0.0.10
  record: ^5.1.2
  http: ^1.2.0
  qr_flutter: ^4.1.0
  uuid: ^4.5.1
  path_provider: ^2.1.5
  audioplayers: ^6.5.1
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/main_page_01.mp4
    - assets/images/payments/
    - assets/fonts/
    - assets/sounds/notification_sound.mp3
    - assets/sounds/new-notification-2.mp3
  fonts:
    - family: Rudaw
      fonts:
        - asset: assets/fonts/RudawRegular.ttf
        # Uncomment if you have RudawBold.ttf:
        # - asset: assets/fonts/RudawBold.ttf
        #   weight: 700